# Generated by Django 5.1.7 on 2025-04-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_purchaseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
